config/routes.rb
Rails.application.routes.draw do
  resources :todo_items
  resources :days
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :todo_items
  has_many :days, through: :todo_items
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :todo_items
  has_many :categories, through: :todo_items
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :category
  belongs_to :day 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    # @category = Category.update(category_params)
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.all
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.create(day_params)
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    # @day = Day.update(day_params)
  end

  def show
    @day = Day.find(params[:id])
  end

  def destroy
    @day = Day.find(params[:id])
  end

  private

  def day_params
    params.require(:day).permit(:name)
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @todo_items = TodoItem.all
  end

  def new
    @todo_item = TodoItem.new
    @categories = Category.all
    @days = Day.all
  end

  def create
    @todo_item = TodoItem.create(todo_item_params)
    redirect_to todo_item_path(@todo_item)
  end

  def edit
    @todo_item = TodoItem.find(params[:id])
    @categories = Category.all
    @days = Day.all
  end

  def update
    @todo_item = TodoItem.find(params[:id])
    @todo_item.update(todo_item_params)
    redirect_to todo_item_path(@todo_item)
  end

  def show
    @todo_item = TodoItem.find(params[:id])
    @todo_items = TodoItem.all
  end

  def destroy
    @todo_items = TodoItem.all
    @todo_item = TodoItem.find(params[:id])
    @todo_item.destroy
    redirect_to todo_items_path(@todo_items)
  end

  private

  def todo_item_params
    params.require(:todo_item).permit(:title, :description, :category_id, :day_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/categories/index.html.erb
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category)%></li>
  <%end%>
</ul>

app/views/categories/new.html.erb
<h1>Create Category</h1>

<%= form_for @category do |f| %>
  <%=f.label "Category"%>
  <%=f.text_field :name%>

  <%=f.submit%>
<%end%>

app/views/categories/show.html.erb
<h1><%=@category.name%></h1>

app/views/days/index.html.erb
<ul>
  <% @days.each do |day| %>
    <li><%= link_to day.name, day_path(day)%></li>
  <%end%>
</ul>

app/views/days/new.html.erb
<h1>Create A Day</h1>

<%= form_for @day do |f| %>
  <%=f.label "Day"%>
  <%=f.text_field :name%>

  <%=f.submit%>
<%end%>

app/views/days/show.html.erb
<h1><%=@day.name%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for @todo_item do |f|%>
  <%=f.label "Title"%><br>
  <%=f.text_field :title%><br>

  <%=f.label "Description"%><br>
  <%=f.text_area :description%><br>

  <%=f.label "Category"%><br>
  <%=f.collection_select :category_id, @categories, :id, :name%><br>

  <%=f.label "Day"%><br>
  <%=f.collection_select :day_id, @days, :id, :name%><br>

  <%=f.submit %>

<%end%>

app/views/todo_items/edit.html.erb
<h1>Update Todo</h1>

<%= render "form"%>

app/views/todo_items/index.html.erb
<ul>
  <% @todo_items.each do |todo_item| %>
    <li><%= link_to todo_item.title, todo_item_path(todo_item)%></li>
  <%end%>
</ul>
<button><%=link_to '+ Create New Todo', new_todo_item_path(@todo_items)%></button>

app/views/todo_items/new.html.erb
<h1>Create A Todo</h1>

<%= render "form"%>

app/views/todo_items/show.html.erb
<h1><%=@todo_item.title%></h1>
<hr>

<p><%=@todo_item.description%></p>
<h3>Category: </h3><%=@todo_item.category.name%><br>
<h3>Due Day: </h3><%=@todo_item.day.name%><br><br>

<button><%= link_to 'Edit', edit_todo_item_path(@todo_item) %></button><br><br>


<form method="POST" action="/todo_items/<%=@todo_item.id%>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete">
</form><br><br><br>

<button><%= link_to "Delete", todo_item_path(@todo_item), method: :delete, data: { confirm: "Are you sure?" } %></button><br><br>


<button><%= link_to '<-- Go Back', todo_items_path(@todo_items) %></button><br><br>